//! AndroidX preference host shims.

use crate::vm::native::*;

pub(crate) const TABLE: &[NativeEntry] = &[
    ne!(
        "Landroidx/preference/Preference;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setKey",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setSummary",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setDefaultValue",
        "(Ljava/lang/Object;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "getContext",
        "()Landroid/content/Context;",
        true,
        crate::vm::native::android::prefs_ctx
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setKey",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setSummary",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setDefaultValue",
        "(Ljava/lang/Object;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
];
