//! AndroidX preference host shims.

use crate::vm::native::*;

pub(crate) const TABLE: &[NativeEntry] = &[
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "addPreference",
        "(Landroidx/preference/Preference;)Z",
        true,
        crate::vm::native::android::prefs_add_preference
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setOnBindEditTextListener",
        "(Landroidx/preference/EditTextPreference$OnBindEditTextListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setDialogMessage",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setDialogTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setText",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setEnabled",
        "(Z)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "setEntries",
        "([Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_entries
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "setEntryValues",
        "([Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_entry_values
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "getEntries",
        "()[Ljava/lang/CharSequence;",
        true,
        crate::vm::native::android::prefs_get_entries
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "getEntryValues",
        "()[Ljava/lang/CharSequence;",
        true,
        crate::vm::native::android::prefs_get_entry_values
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "getKey",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::prefs_get_key
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "findIndexOfValue",
        "(Ljava/lang/String;)I",
        true,
        crate::vm::native::android::prefs_find_index_of_value
    ),
    ne!(
        "Landroidx/preference/ListPreference;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "setEntries",
        "([Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_entries
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "setEntryValues",
        "([Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_entry_values
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "getEntries",
        "()[Ljava/lang/CharSequence;",
        true,
        crate::vm::native::android::prefs_get_entries
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "getEntryValues",
        "()[Ljava/lang/CharSequence;",
        true,
        crate::vm::native::android::prefs_get_entry_values
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "setEnabled",
        "(Z)V",
        true,
        crate::vm::native::android::prefs_set_enabled
    ),
    ne!(
        "Landroidx/preference/MultiSelectListPreference;",
        "setDialogTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/CheckBoxPreference;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/CheckBoxPreference;",
        "setVisible",
        "(Z)V",
        true,
        crate::vm::native::android::prefs_set_visible
    ),
    ne!(
        "Landroidx/preference/CheckBoxPreference;",
        "getKey",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::prefs_get_key
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "getKey",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::prefs_get_key
    ),
    ne!(
        "Landroidx/preference/EditTextPreference;",
        "setOnPreferenceClickListener",
        "(Landroidx/preference/Preference$OnPreferenceClickListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setSummaryOff",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setSummaryOn",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setOnPreferenceChangeListener",
        "(Landroidx/preference/Preference$OnPreferenceChangeListener;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setKey",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::prefs_set_key
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_title
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setSummary",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_summary
    ),
    ne!(
        "Landroidx/preference/Preference;",
        "setDefaultValue",
        "(Ljava/lang/Object;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "getContext",
        "()Landroid/content/Context;",
        true,
        crate::vm::native::android::prefs_ctx
    ),
    ne!(
        "Landroidx/preference/PreferenceScreen;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_title
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "<init>",
        "(Landroid/content/Context;)V",
        true,
        crate::vm::native::android::prefs_obj
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setKey",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::prefs_set_key
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setTitle",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_title
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setSummary",
        "(Ljava/lang/CharSequence;)V",
        true,
        crate::vm::native::android::prefs_set_summary
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setDefaultValue",
        "(Ljava/lang/Object;)V",
        true,
        crate::vm::native::android::prefs_set
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setEnabled",
        "(Z)V",
        true,
        crate::vm::native::android::prefs_set_enabled
    ),
    ne!(
        "Landroidx/preference/SwitchPreferenceCompat;",
        "setVisible",
        "(Z)V",
        true,
        crate::vm::native::android::prefs_set_visible
    ),
];
