//! Kotlin collections bridge registrations.
use crate::vm::native::*;

pub(crate) const TABLE: &[NativeEntry] = &[
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "asSequence",
        "(Ljava/lang/Iterable;)Lkotlin/sequences/Sequence;",
        false,
        super::sequence_as_sequence
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "flatten",
        "(Ljava/lang/Iterable;)Ljava/util/List;",
        false,
        super::collections_flatten
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "toList",
        "(Ljava/lang/Iterable;)Ljava/util/List;",
        false,
        super::collections_to_list_iterable
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "sorted",
        "(Ljava/lang/Iterable;)Ljava/util/List;",
        false,
        super::collections_sorted
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "take",
        "(Ljava/lang/Iterable;I)Ljava/util/List;",
        false,
        super::collections_take
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "drop",
        "(Ljava/lang/Iterable;I)Ljava/util/List;",
        false,
        super::collections_drop
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "asReversed",
        "(Ljava/util/List;)Ljava/util/List;",
        false,
        super::collections_as_reversed
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "reversed",
        "(Ljava/lang/Iterable;)Ljava/util/List;",
        false,
        super::collections_reversed
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "removeAll",
        "(Ljava/util/List;Lkotlin/jvm/functions/Function1;)Z",
        false,
        super::collections_remove_all
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "plus",
        "(Ljava/lang/Iterable;Ljava/lang/Iterable;)Ljava/util/List;",
        false,
        super::collections_plus_iterable
    ),
    ne!(
        "Lkotlin/collections/CollectionsKt;",
        "getLastIndex",
        "(Ljava/util/List;)I",
        false,
        super::collections_get_last_index
    ),
];
