//! java.io.File host shims.

use crate::vm::native::*;

/// Implementation delegates to the Android sandbox shims.
#[cfg(feature = "android")]
pub(crate) const TABLE: &[NativeEntry] = &[
    ne!(
        "Ljava/io/File;",
        "<init>",
        "(Ljava/lang/String;)V",
        true,
        crate::vm::native::android::file_init_string
    ),
    ne!(
        "Ljava/io/File;",
        "<init>",
        "(Ljava/io/File;Ljava/lang/String;)V",
        true,
        crate::vm::native::android::file_init_parent_string
    ),
    ne!(
        "Ljava/io/File;",
        "<init>",
        "(Ljava/lang/String;Ljava/lang/String;)V",
        true,
        crate::vm::native::android::file_init_parent_strings
    ),
    ne!(
        "Ljava/io/File;",
        "mkdirs",
        "()Z",
        true,
        crate::vm::native::android::file_mkdirs
    ),
    ne!(
        "Ljava/io/File;",
        "exists",
        "()Z",
        true,
        crate::vm::native::android::file_exists
    ),
    ne!(
        "Ljava/io/File;",
        "lastModified",
        "()J",
        true,
        crate::vm::native::android::file_last_modified
    ),
    ne!(
        "Ljava/io/File;",
        "length",
        "()J",
        true,
        crate::vm::native::android::file_length
    ),
    ne!(
        "Ljava/io/File;",
        "isDirectory",
        "()Z",
        true,
        crate::vm::native::android::file_is_directory
    ),
    ne!(
        "Ljava/io/File;",
        "isFile",
        "()Z",
        true,
        crate::vm::native::android::file_is_file
    ),
    ne!(
        "Ljava/io/File;",
        "createNewFile",
        "()Z",
        true,
        crate::vm::native::android::file_create_new_file
    ),
    ne!(
        "Ljava/io/File;",
        "delete",
        "()Z",
        true,
        crate::vm::native::android::file_delete
    ),
    ne!(
        "Ljava/io/File;",
        "getAbsolutePath",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::file_get_absolute_path
    ),
    ne!(
        "Ljava/io/File;",
        "getCanonicalPath",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::file_get_canonical_path
    ),
    ne!(
        "Ljava/io/File;",
        "getPath",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::file_get_path
    ),
    ne!(
        "Ljava/io/File;",
        "getName",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::file_get_name
    ),
    ne!(
        "Ljava/io/File;",
        "getParent",
        "()Ljava/lang/String;",
        true,
        crate::vm::native::android::file_get_parent
    ),
    ne!(
        "Ljava/io/File;",
        "getParentFile",
        "()Ljava/io/File;",
        true,
        crate::vm::native::android::file_get_parent_file
    ),
    ne!(
        "Ljava/io/File;",
        "createTempFile",
        "(Ljava/lang/String;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;",
        false,
        crate::vm::native::android::file_create_temp_file
    ),
    ne!(
        "Ljava/io/File;",
        "renameTo",
        "(Ljava/io/File;)Z",
        true,
        crate::vm::native::android::file_rename_to
    ),
    ne!(
        "Lkotlin/io/FilesKt;",
        "resolve",
        "(Ljava/io/File;Ljava/lang/String;)Ljava/io/File;",
        false,
        crate::vm::native::android::fileskt_resolve
    ),
];
