#!/usr/bin/env python3
"""Final native-table split: keiyoushi.rs -> keiyoushi(kanade)/okhttp/jsoup/android/kotlin,
mod.rs NATIVE_TABLE -> kotlin.rs/injekt.rs, rewrite mod.rs + package mod files.

Run AFTER tools/split_lang.py and tools/split_util.py. One-shot; not idempotent.
"""
import os
import re
import sys

ROOT = os.environ.get('OUT', 'src/vm/native')

def read(p):
    """Read a source file from git HEAD (the pre-refactor tree); fall back to the
    on-disk output tree for files generated by an earlier split script."""
    import subprocess
    disk = p
    if p.startswith(ROOT):  # remap OUT back to the repo-relative source path
        p = 'src/vm/native' + p[len(ROOT):]
    r = subprocess.run(['git', 'show', f'HEAD:{p}'], capture_output=True, text=True)
    if r.returncode == 0:
        return r.stdout.split('\n')
    with open(disk) as f:  # generated by an earlier split script
        return f.read().split('\n')

def write(p, text):
    with open(p, 'w') as f:
        f.write(text)

def lines_1based(src, a, b):
    """1-based inclusive slice."""
    return src[a - 1:b]

def lines_1based_keep(src, *ranges):
    out = []
    for a, b in ranges:
        out.extend(src[a - 1:b])
    return out

def banner(title):
    return f'// ---------------------------------------------------------------------------\n// {title}\n// ---------------------------------------------------------------------------\n\n'

# ---------------------------------------------------------------- sources
ky = read(f'{ROOT}/keiyoushi.rs')
mod = read(f'{ROOT}/mod.rs')
ok = read(f'{ROOT}/okhttp.rs')
kt = read(f'{ROOT}/kotlin.rs')
sa = read(f'{ROOT}/kotlin_stringskt_append.rs')

# split a ne!(...) entry line into fields for keying
def entry_key(line):
    m = re.search(r'ne!\("([^"]+)",\s*"([^"]+)",\s*"([^"]+)"', line)
    return (m.group(1), m.group(2), m.group(3)) if m else None

def entry_class(line):
    m = re.search(r'ne!\("([^"]+)",', line)
    return m.group(1) if m else None

def split_table_entries(src, start_idx, keep_fn, drop_fn=None):
    """Scan table entries (lines starting with ne! or comments) from start_idx;
    route each ne! line via keep_fn(cls)->bool. Returns (keep_lines, moved_by_keep).
    """
    keep, moved = [], []
    for line in src[start_idx:]:
        stripped = line.strip()
        if stripped.startswith('//') or not stripped:
            continue
        if stripped.startswith('ne!('):
            cls = entry_class(line)
            if drop_fn and drop_fn(line):
                continue
            if keep_fn(cls):
                keep.append(line)
            else:
                moved.append(line)
    return keep, moved

def strip_blank_ends(lines):
    while lines and lines[0].strip() == '':
        lines.pop(0)
    while lines and lines[-1].strip() == '':
        lines.pop()
    return lines

# ---------------------------------------------------------------- keiyoushi.rs table entries
TABLE_START = next(i for i, l in enumerate(ky) if 'pub const KEIYOUSHI_TABLE' in l)
def is_kanade(cls):
    return cls.startswith('Leu/kanade/') and not cls.startswith('Leu/kanade/tachiyomi/util/JsoupExtensionsKt')
def is_jsoup(cls):
    return cls.startswith('Lorg/jsoup/') or cls.startswith('Leu/kanade/tachiyomi/util/JsoupExtensionsKt')
def is_okhttp3(cls):
    return cls.startswith('Lokhttp3/')
def is_kotlin(cls):
    return cls.startswith('Lkotlin/')
def is_android(cls):
    return cls.startswith('Landroid')  # android. + androidx.

keep_kanade, moved_entries = [], []
buckets = {'okhttp3': [], 'jsoup': [], 'kotlin': [], 'android': []}
for line in ky[TABLE_START:]:
    stripped = line.strip()
    if not stripped.startswith('ne!('):
        continue
    cls = entry_class(line)
    if is_kanade(cls):
        keep_kanade.append(line)
    elif is_jsoup(cls):
        buckets['jsoup'].append(line)
    elif is_okhttp3(cls):
        buckets['okhttp3'].append(line)
    elif is_kotlin(cls):
        buckets['kotlin'].append(line)
    elif is_android(cls):
        buckets['android'].append(line)
    else:
        print('UNROUTED:', line.strip()[:100])
        sys.exit(1)

# OKHTTP_TABLE entries from mod.rs
okhttp_tbl_start = next(i for i, l in enumerate(mod) if 'pub const OKHTTP_TABLE' in l)
okhttp_tbl_end = next(i for i, l in enumerate(mod[okhttp_tbl_start:], okhttp_tbl_start) if l.strip() == '];')
mod_ok = mod[okhttp_tbl_start:okhttp_tbl_end + 1]
ok_kanade, ok_okhttp3 = [], []
for line in mod_ok:
    stripped = line.strip()
    if not stripped.startswith('ne!('):
        continue
    cls = entry_class(line)
    if is_kanade(cls) or cls.startswith('Leu/kanade/'):
        ok_kanade.append(line)
    elif is_okhttp3(cls):
        ok_okhttp3.append(line)
    else:
        print('UNROUTED OKHTTP_TABLE:', line.strip()[:100])
        sys.exit(1)

# dedupe okhttp3 entries: keiyoushi version wins (it was registered later)
seen = set()
ok_okhttp3_final = []
for line in buckets['okhttp3']:
    key = entry_key(line)
    seen.add(key)
    ok_okhttp3_final.append(line)
dropped = []
for line in ok_okhttp3:
    key = entry_key(line)
    if key in seen:
        dropped.append(key)
        continue
    seen.add(key)
    ok_okhttp3_final.append(line)

# eu.kanade entries from OKHTTP_TABLE: skip HttpSource getHeaders (dup, default wins)
for line in ok_kanade:
    key = entry_key(line)
    dup = any(entry_key(k) == key for k in keep_kanade)
    if dup:
        dropped.append(key)
        continue
    keep_kanade.append(line)

print(f'kanade entries: {len(keep_kanade)}  okhttp3: {len(ok_okhttp3_final)}  '
      f'jsoup: {len(buckets["jsoup"])}  kotlin: {len(buckets["kotlin"])}  android: {len(buckets["android"])}')
print('dropped dup keys:', dropped)


def extract_fns(lines, names):
    """Return just the whole fns (signature through closing brace) whose signature
    contains any of `names`, in order."""
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if any(n in line for n in names):
            depth = 0
            start = i
            while i < len(lines):
                depth += lines[i].count('{') - lines[i].count('}')
                i += 1
                if depth == 0:
                    break
            out.extend(lines[start:i])
        else:
            i += 1
    return out


def drop_fns(lines, names):
    """Remove whole fns (signature line through the matching closing brace) whose
    signature contains any of `names`."""
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if any(n in line for n in names):
            depth = 0
            start = i
            while i < len(lines):
                depth += lines[i].count('{') - lines[i].count('}')
                i += 1
                if depth == 0:
                    break
        else:
            out.append(line)
            i += 1
    return out

# ---------------------------------------------------------------- 1. jsoup.rs
jsoup_impls = lines_1based_keep(ky, (1148, 1276), (1322, 1682))
jsoup_impls = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in jsoup_impls]
jsoup_impls = [l if l.startswith('fn ') else l for l in jsoup_impls]  # keep private fns private
jsoup_table = buckets['jsoup']
jsoup_body = banner('org.jsoup on top of dom_query (mirrors rakuyuki html_element.rs)') + \
    '\n'.join(jsoup_impls) + '\n\n' + \
    banner('org.jsoup native table') + \
    'pub(crate) const JSOUP_TABLE: &[NativeEntry] = &[\n' + \
    '\n'.join(jsoup_table) + '\n];\n'
write(f'{ROOT}/jsoup.rs',
      '//! org.jsoup host shims on top of dom_query.\n\n'
      'use super::*;\n'
      'use dom_query::{Document, Matcher, NodeId, NodeRef, Selection};\n\n'
      'use crate::vm::object::JsoupDocRef;\n\n' + jsoup_body)
print('wrote jsoup.rs')

# ---------------------------------------------------------------- 2. android.rs
android_fns = lines_1based_keep(ky, (1701, 1719), (1741, 1744))
android_table = buckets['android']
write(f'{ROOT}/android.rs',
      '//! android / androidx framework host shims (keiyoushi feature).\n\n'
      'use super::*;\n\n' +
      banner('android framework') + '\n'.join(android_fns) + '\n\n' +
      banner('android native table') +
      'pub(crate) const ANDROID_TABLE: &[NativeEntry] = &[\n' +
      '\n'.join(android_table) + '\n];\n')
print('wrote android.rs')

# ---------------------------------------------------------------- 3. injekt.rs
injekt_start = next(i for i, l in enumerate(mod) if '// injekt DI' in l)
injekt_end = next(i for i, l in enumerate(mod[injekt_start:], injekt_start) if l.startswith('fn boxed'))
injekt_fns = mod[injekt_start:injekt_end]
injekt_fns = strip_blank_ends(injekt_fns)
nat_tbl_start = next(i for i, l in enumerate(mod) if 'pub const NATIVE_TABLE' in l)
injekt_entries = []
for line in mod[nat_tbl_start:]:
    cls = entry_class(line)
    if cls and cls.startswith('Luy/kohesive/injekt'):
        injekt_entries.append(line)
write(f'{ROOT}/injekt.rs',
      '//! injekt (kohesive) DI host shims.\n\n'
      'use super::*;\n\n' +
      banner('injekt DI (kohesive)') + '\n'.join(injekt_fns) + '\n\n' +
      banner('injekt native table') +
      'pub(crate) const INJEKT_TABLE: &[NativeEntry] = &[\n' +
      '\n'.join(injekt_entries) + '\n];\n')
print('wrote injekt.rs')

# ---------------------------------------------------------------- 4. okhttp.rs
# keep only okhttp3 fns of current okhttp.rs (drop eu.kanade fns + requests_kt_post_default + dup build impl)
ok3_start = next(i for i, l in enumerate(ok) if 'fn okhttp_client_new_builder' in l)
ok3_end = next(i for i, l in enumerate(ok[ok3_start:], ok3_start) if 'fn requests_kt_post_default' in l)
keep_ok = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in drop_fns(ok[ok3_start:ok3_end], ('fn okhttp_request_builder_build',))]
ok_extra = lines_1based_keep(ky, (91, 116), (148, 513))
ok_extra = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in ok_extra]
ok_extra = [re.sub(r'^fn (form_body_to_string|request_parts)', r'pub(crate) fn \1', l) for l in ok_extra]
okhttp_body = banner('HTTP bridge helpers') + '\n'.join(ok_extra) + '\n\n' + \
    banner('OkHttpClient / FormBody / HttpUrl / builder shims') + '\n'.join(keep_ok) + '\n\n' + \
    banner('okhttp3 native table') + \
    'pub(crate) const OKHTTP_TABLE: &[NativeEntry] = &[\n' + \
    '\n'.join(ok_okhttp3_final) + '\n];\n'
write(f'{ROOT}/okhttp.rs',
      '//! Host shims for the OkHttp network stack used by extensions.\n'
      '//! Requests are never executed; the client/builder classes only carry\n'
      '//! interceptor lists so extension `<init>` code can run.\n\n'
      'use super::*;\n\n' + okhttp_body)
print('wrote okhttp.rs')

# ---------------------------------------------------------------- 5. kotlin.rs
stringskt = lines_1based(ky, 1277, 1320)
duration = lines_1based(ky, 1683, 1700)
sa_body = [l for l in sa if not l.startswith('use ')]
kt_entries = []
for line in mod[nat_tbl_start:]:
    cls = entry_class(line)
    if cls and cls.startswith('Lkotlin/'):
        kt_entries.append(line)
kt_entries.extend(buckets['kotlin'])
# kotlin table entries may reference fns defined elsewhere (object_noop) via glob
kt = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in kt]
kt_body = '\n'.join(kt) + '\n\n' + \
    banner('kotlin.text.StringsKt synthetic default-arg shims (mask bit 2 = ignoreCase default false)') + \
    '\n'.join(stringskt) + '\n\n' + \
    banner('kotlin.text.StringsKt append (from string.rs, removed by split_lang.py)') + \
    '\n'.join(sa_body) + '\n\n' + \
    banner('kotlin.time.Duration value-class methods (host stdlib)') + '\n'.join(duration) + '\n\n' + \
    banner('kotlin stdlib native table') + \
    'pub(crate) const KOTLIN_TABLE: &[NativeEntry] = &[\n' + \
    '\n'.join(kt_entries) + '\n];\n'
write(f'{ROOT}/kotlin.rs', kt_body)
print('wrote kotlin.rs')

# ---------------------------------------------------------------- 6. keiyoushi.rs (eu.kanade only)
moved_okhttp = lines_1based(ky, 91, 116)
moved_okhttp = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in moved_okhttp]
kanade_fns = lines_1based_keep(ky, (1, 62), (63, 90), (117, 147), (514, 622), (623, 1147), (1721, 1740))
kanade_fns = [re.sub(r'\bcollections::list_alloc\b', 'list_alloc', l) for l in kanade_fns]
kanade_fns = [l for l in kanade_fns if 'dom_query' not in l and 'JsoupDocRef' not in l]
# eu.kanade impls moved out of okhttp.rs
moved_from_okhttp = extract_fns(ok, ('fn http_source_get_network', 'fn network_helper_get_client', 'fn requests_kt_post_default'))
keep_kanade_body = '\n'.join(kanade_fns) + '\n\n' + banner('eu.kanade network helpers (from OkHttp shim)') + '\n'.join(moved_from_okhttp) + '\n\n' + banner('KEIYOUSHI_TABLE') + 'pub const KEIYOUSHI_TABLE: &[NativeEntry] = &[\n' + '\n'.join(keep_kanade) + '\n];\n'
# fix the doc comment at the top: no longer about jsoup/okhttp stack
doc_lines = keep_kanade_body.split('\n')
i = 0
while i < len(doc_lines) and (doc_lines[i].startswith('//!') or doc_lines[i].strip() == ''):
    i += 1
new_doc = [
    '//! Host shims for the eu.kanade.tachiyomi (mihon/keiyoushi) extension API surface.',
    '//!',
    '//! HTTP requests are not executed by the VM: the bridge registers an HTTP',
    '//! callback on [`Vm::http`] and triggers it through the',
    '//! `RequestsKt.__host_execute` native.',
]
keep_kanade_body = '\n'.join(new_doc) + '\n\n' + '\n'.join(doc_lines[i:])
keep_kanade_body = re.sub(r'\n{3,}', '\n\n', keep_kanade_body).rstrip() + '\n'
write(f'{ROOT}/keiyoushi.rs', keep_kanade_body)
print('wrote keiyoushi.rs')
