#!/usr/bin/env python3
"""Generate java/lang/*.rs per-class files + java/io.rs (PrintStream).

Usage: python3 split_lang.py
"""
import os, re

ROOT = os.environ.get('OUT', 'src/vm/native')

def read(p):
    """Read a source file from git HEAD (the pre-refactor tree); fall back to the
    on-disk output tree for files generated by an earlier split script."""
    import subprocess
    disk = p
    if p.startswith(ROOT):  # remap OUT back to the repo-relative source path
        p = 'src/vm/native' + p[len(ROOT):]
    r = subprocess.run(['git', 'show', f'HEAD:{p}'], capture_output=True, text=True)
    if r.returncode == 0:
        return r.stdout.split('\n')
    with open(disk) as f:  # generated by an earlier split script
        return f.read().split('\n')

def write(p, content):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as f:
        f.write(content)

def slice_text(lines, start, end):
    return '\n'.join(lines[start-1:end]) + '\n'

# ---------------- entries from NATIVE_TABLE (mod.rs 949-1635) ----------------
def parse_table_entries(mod_lines, start, end):
    entries = []
    for ln in mod_lines[start-1:end]:
        m = re.search(r'ne!\("([^"]+;)"', ln)
        if m:
            entries.append((m.group(1), ln))
    return entries

mod = read(f'{ROOT}/mod.rs')
nat_entries = parse_table_entries(mod, 949, 1635)
by_class = {}
for cls, text in nat_entries:
    by_class.setdefault(cls, []).append(text)

def table_for(cls):
    return by_class.get(cls, [])

HEADER = 'use crate::vm::native::*;\n\n// {title} host shims.\n\n'

def emit_class_file(path, title, cls, fn_text, extra_comment=''):
    body = ''
    if extra_comment:
        body += extra_comment + '\n'
    fn_text = re.sub(r'^//! ', '// ', fn_text, flags=re.M)  # inner docs after items are E0753
    fn_text = '\n'.join(l for l in fn_text.split('\n') if l.strip() not in ('use crate::vm::native::*;', 'use super::*;'))
    body += fn_text
    table = table_for(cls)
    if table:
        body += f'\n/// Native methods for {cls}\n'
        body += f'pub(crate) const TABLE: &[NativeEntry] = &[\n'
        for t in table:
            body += t.rstrip() + '\n'
        body += '];\n'
    write(path, HEADER.format(title=title) + body)

lang = read(f'{ROOT}/lang.rs')

def lang_slice(a, b):
    return slice_text(lang, a, b)

# ---- java.lang.Object (3-55) ----
# object.rs keeps the original '//!' header (hand-fixed tree)
_obj_header = '//! java.lang.Object host shims.\n\nuse crate::vm::native::*;\n\n'
_obj_tbl = table_for('Ljava/lang/Object;')
_obj_body = lang_slice(3, 55)
if _obj_tbl:
    _obj_body += '\n/// Native methods for Ljava/lang/Object;\n'
    _obj_body += 'pub(crate) const TABLE: &[NativeEntry] = &[\n'
    for _t in _obj_tbl:
        _obj_body += _t.rstrip() + '\n'
    _obj_body += '];\n'
write(f'{ROOT}/java/lang/object.rs', _obj_header + _obj_body)
# ---- java.lang.Class (57-350) ----
emit_class_file(f'{ROOT}/java/lang/class.rs', 'java.lang.Class', 'Ljava/lang/Class;', lang_slice(57, 350))
# ---- java.lang.Throwable (351-491) ----
emit_class_file(f'{ROOT}/java/lang/throwable.rs', 'java.lang.Throwable', 'Ljava/lang/Throwable;', lang_slice(351, 491))
# ---- java.lang.System (492-677) ----
emit_class_file(f'{ROOT}/java/lang/system.rs', 'java.lang.System', 'Ljava/lang/System;', lang_slice(492, 677))
# ---- java.io.PrintStream (678-722) -> java/io.rs ----
ps_fn = lang_slice(678, 722)
table_io = table_for('Ljava/io/PrintStream;')
io_body = ps_fn
if table_io:
    io_body += '\n/// Native methods for Ljava/io/PrintStream;\n'
    io_body += 'pub(crate) const TABLE: &[NativeEntry] = &[\n'
    for t in table_io:
        io_body += t.rstrip() + '\n'
    io_body += '];\n'
write(f'{ROOT}/java/io.rs', HEADER.format(title='java.io.PrintStream') + io_body)
# ---- boxed helpers (728-743) ----
box_helpers = lang_slice(728, 743)
# ---- Integer (744-841 + signum 1396-1399) ----
emit_class_file(f'{ROOT}/java/lang/integer.rs', 'java.lang.Integer', 'Ljava/lang/Integer;',
                box_helpers + lang_slice(744, 841) + lang_slice(1396, 1399))
# ---- Long (842-923 + signum 1400-1404) ----
emit_class_file(f'{ROOT}/java/lang/long.rs', 'java.lang.Long', 'Ljava/lang/Long;',
                lang_slice(842, 923) + lang_slice(1400, 1404))
# ---- Short (924-949) ----
emit_class_file(f'{ROOT}/java/lang/short.rs', 'java.lang.Short', 'Ljava/lang/Short;', lang_slice(924, 949))
# ---- Byte (950-975) ----
emit_class_file(f'{ROOT}/java/lang/byte.rs', 'java.lang.Byte', 'Ljava/lang/Byte;', lang_slice(950, 975))
# ---- Character (976-1068) ----
emit_class_file(f'{ROOT}/java/lang/character.rs', 'java.lang.Character', 'Ljava/lang/Character;', lang_slice(976, 1068))
# ---- Boolean (1069-1104) ----
emit_class_file(f'{ROOT}/java/lang/boolean.rs', 'java.lang.Boolean', 'Ljava/lang/Boolean;', lang_slice(1069, 1104))
# ---- Float (1105-1203) ----
emit_class_file(f'{ROOT}/java/lang/float.rs', 'java.lang.Float', 'Ljava/lang/Float;', lang_slice(1105, 1203))
# ---- Double (1204-1303) ----
emit_class_file(f'{ROOT}/java/lang/double.rs', 'java.lang.Double', 'Ljava/lang/Double;', lang_slice(1204, 1303))
# ---- Thread (1305-1346) ----
emit_class_file(f'{ROOT}/java/lang/thread.rs', 'java.lang.Thread', 'Ljava/lang/Thread;', lang_slice(1305, 1346))
# ---- java.lang.Enum (1347-1395) ----
emit_class_file(f'{ROOT}/java/lang/enum.rs', 'java.lang.Enum', 'Ljava/lang/Enum;', lang_slice(1347, 1395))

# ---- java.lang.String from string.rs ----
# (3-544): string fns through string_format. The first string_index_of_str
# (211-224) is dropped from its original spot and re-inserted after
# string_format; the sb_index_of tail (799-802) is excluded; (803-812): misc.
string = read(f'{ROOT}/string.rs')
emit_class_file(f'{ROOT}/java/lang/string.rs', 'java.lang.String', 'Ljava/lang/String;',
                slice_text(string, 3, 210) + slice_text(string, 224, 544) + slice_text(string, 211, 223) + slice_text(string, 803, 812))
# ---- java.lang.StringBuilder from string.rs (545-798; strings_append_array
# at 681-704 is kotlin.text.StringsKt -> kotlin.rs, exclude it) ----
sb_part1 = slice_text(string, 545, 678)
sb_part2 = slice_text(string, 705, 802)
emit_class_file(f'{ROOT}/java/lang/stringbuilder.rs', 'java.lang.StringBuilder', 'Ljava/lang/StringBuilder;',
                sb_part1 + sb_part2)
# ---- kotlin.text.StringsKt.append (681-704) -> kotlin.rs (appended later) ----
with open(f'{ROOT}/kotlin_stringskt_append.rs', 'w') as f:
    f.write(slice_text(string, 681, 704))

# ---- java.lang.Math from math.rs ----
math = read(f'{ROOT}/math.rs')
emit_class_file(f'{ROOT}/java/lang/math.rs', 'java.lang.Math', 'Ljava/lang/Math;', slice_text(math, 3, 189))

# ---- java/lang/mod.rs ----
lang_mods = ['object', 'string', 'stringbuilder', 'class', 'enum', 'throwable',
             'system', 'thread', 'math', 'integer', 'long', 'short', 'byte',
             'character', 'boolean', 'float', 'double']
lines = []
for m in lang_mods:
    lines.append(f'mod {m};')
lines.append('')
for m in lang_mods:
    lines.append(f'pub(crate) use {m}::*;')
lines.append('')
tables = ['object::TABLE', 'string::TABLE', 'stringbuilder::TABLE', 'class::TABLE',
          'enum::TABLE', 'throwable::TABLE', 'system::TABLE', 'thread::TABLE',
          'math::TABLE', 'integer::TABLE', 'long::TABLE', 'short::TABLE',
          'byte::TABLE', 'character::TABLE', 'boolean::TABLE', 'float::TABLE',
          'double::TABLE']
lines.append('/// All java.lang native tables, grouped for `register`.')
lines.append('pub(crate) const LANG_TABLE: &[&[NativeEntry]] = &[')
for t in tables:
    lines.append(f'    {t},')
lines.append('];')
lines.append('')
write(f'{ROOT}/java/lang/mod.rs', '\n'.join(lines))

# ---- java/mod.rs (placeholder; extended later) ----
java_lines = [
    'use crate::vm::native::*;',
    '',
    'mod lang;',
    'mod io;',
    '',
    'pub(crate) use self::io::*;',
    'pub(crate) use lang::*;',
    '',
    '/// All java.* native tables, grouped for `register`.',
    'pub(crate) const JAVA_TABLE: &[&[NativeEntry]] = &[',
    '    lang::LANG_TABLE,',
    '    &[io::TABLE],',
    '];',
    '',
]
write(f'{ROOT}/java/mod.rs', '\n'.join(java_lines))

print('done')
