#!/usr/bin/env python3
"""Generate java/util/*, java/text/*, java/nio.rs, and top up java/io.rs.

Reads entries from NATIVE_TABLE (mod.rs) by class and splits impl files
by line ranges.
"""
import os, re

ROOT = os.environ.get('OUT', 'src/vm/native')

def read(p):
    """Read a source file from git HEAD (the pre-refactor tree); fall back to the
    on-disk output tree for files generated by an earlier split script."""
    import subprocess
    disk = p
    if p.startswith(ROOT):  # remap OUT back to the repo-relative source path
        p = 'src/vm/native' + p[len(ROOT):]
    r = subprocess.run(['git', 'show', f'HEAD:{p}'], capture_output=True, text=True)
    if r.returncode == 0:
        return r.stdout.split('\n')
    with open(disk) as f:  # generated by an earlier split script
        return f.read().split('\n')

def write(p, content):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as f:
        f.write(content)

def slice_text(lines, start, end):
    return '\n'.join(lines[start-1:end]) + '\n'

def parse_table_entries(mod_lines, start, end):
    entries = []
    for ln in mod_lines[start-1:end]:
        m = re.search(r'ne!\("([^"]+;)"', ln)
        if m:
            entries.append((m.group(1), ln))
    return entries

mod = read(f'{ROOT}/mod.rs')
nat_entries = parse_table_entries(mod, 949, 1635)
by_class = {}
for cls, text in nat_entries:
    by_class.setdefault(cls, []).append(text)

HEADER = 'use crate::vm::native::*;\n\n// {title} host shims.\n\n'

def emit_class_file(path, title, cls, fn_text, extra_comment=''):
    body = ''
    if extra_comment:
        body += extra_comment + '\n'
    fn_text = re.sub(r'^//! ', '// ', fn_text, flags=re.M)  # inner docs after items are E0753
    body += fn_text
    table = by_class.get(cls, [])
    if table:
        body += f'\n/// Native methods for {cls}\n'
        body += 'pub(crate) const TABLE: &[NativeEntry] = &[\n'
        for t in table:
            body += t.rstrip() + '\n'
        body += '];\n'
    write(path, HEADER.format(title=title) + body)

# ---------------- collections.rs -> java/util ---------------- 
coll = read(f'{ROOT}/collections.rs')

# shared helpers (3-40): coll_elems, list_alloc, set_alloc
shared = slice_text(coll, 3, 40)
# ArrayList: list_* impls (41-413)
emit_class_file(f'{ROOT}/java/util/arraylist.rs', 'java.util.ArrayList', 'Ljava/util/ArrayList;',
                slice_text(coll, 41, 413))
# HashMap: map_* impls (414-684) + LinkedHashMap table shares impls
emit_class_file(f'{ROOT}/java/util/hashmap.rs', 'java.util.HashMap', 'Ljava/util/HashMap;',
                slice_text(coll, 414, 684))
emit_class_file(f'{ROOT}/java/util/linkedhashmap.rs', 'java.util.LinkedHashMap', 'Ljava/util/LinkedHashMap;',
                '', extra_comment='// LinkedHashMap shares the map_* impls with HashMap (see hashmap.rs).\n')
# HashSet: set_* impls (685-843) + LinkedHashSet shares impls
emit_class_file(f'{ROOT}/java/util/hashset.rs', 'java.util.HashSet', 'Ljava/util/HashSet;',
                slice_text(coll, 685, 843))
emit_class_file(f'{ROOT}/java/util/linkedhashset.rs', 'java.util.LinkedHashSet', 'Ljava/util/LinkedHashSet;',
                '', extra_comment='// LinkedHashSet shares the set_* impls with HashSet (see hashset.rs).\n')
# Map$Entry: entry_* (844-895)
emit_class_file(f'{ROOT}/java/util/map_entry.rs', 'java.util.Map$Entry', 'Ljava/util/Map$Entry;',
                slice_text(coll, 844, 895))
# Iterator / ListIterator: iter_* (896-988)
emit_class_file(f'{ROOT}/java/util/iterator.rs', 'java.util.Iterator', 'Ljava/util/Iterator;',
                slice_text(coll, 896, 988))
# Collections statics (989-1082)
emit_class_file(f'{ROOT}/java/util/collections.rs', 'java.util.Collections', 'Ljava/util/Collections;',
                slice_text(coll, 989, 1082))
# Arrays statics (1083-1329)
emit_class_file(f'{ROOT}/java/util/arrays.rs', 'java.util.Arrays', 'Ljava/util/Arrays;',
                slice_text(coll, 1083, 1329))

# ---------------- sync.rs -> arraydeque + locks ----------------
sync = read(f'{ROOT}/sync.rs')
emit_class_file(f'{ROOT}/java/util/arraydeque.rs', 'java.util.ArrayDeque', 'Ljava/util/ArrayDeque;',
                slice_text(sync, 3, 70))
emit_class_file(f'{ROOT}/java/util/reentrant_lock.rs', 'java.util.concurrent.locks.ReentrantLock / Condition',
                'Ljava/util/concurrent/locks/ReentrantLock;', slice_text(sync, 71, 114))
# Condition is table-only: condition_* fns live with the lock impls above
emit_class_file(f'{ROOT}/java/util/condition.rs', 'java.util.concurrent.locks.Condition',
                'Ljava/util/concurrent/locks/Condition;',
                '', extra_comment='// Condition shares the condition_* impls with ReentrantLock (see reentrant_lock.rs).\n')
# ListIterator shares iter_* impls (table only)
emit_class_file(f'{ROOT}/java/util/list_iterator.rs', 'java.util.ListIterator', 'Ljava/util/ListIterator;',
                '', extra_comment='// ListIterator shares the iter_* impls with Iterator (see iterator.rs).\n')

# ---------------- regex.rs -> java/util/regex.rs ----------------
regex = read(f'{ROOT}/regex.rs')
# Pattern impls (1-100); Matcher impls (101-353)
emit_class_file(f'{ROOT}/java/util/regex/pattern.rs', 'java.util.regex.Pattern', 'Ljava/util/regex/Pattern;',
                slice_text(regex, 1, 100))
emit_class_file(f'{ROOT}/java/util/regex/matcher.rs', 'java.util.regex.Matcher', 'Ljava/util/regex/Matcher;',
                slice_text(regex, 101, 353))
write(f'{ROOT}/java/util/regex/mod.rs',
      'mod matcher;\nmod pattern;\n\npub(crate) use matcher::*;\npub(crate) use pattern::*;\n')

# ---------------- io.rs splits ----------------
io = read(f'{ROOT}/io.rs')
# Random (84-227)
emit_class_file(f'{ROOT}/java/util/random.rs', 'java.util.Random', 'Ljava/util/Random;',
                slice_text(io, 84, 227))
# Date (229-313)
emit_class_file(f'{ROOT}/java/util/date.rs', 'java.util.Date', 'Ljava/util/Date;',
                slice_text(io, 229, 313))
# Locale (315-370)
emit_class_file(f'{ROOT}/java/util/locale.rs', 'java.util.Locale', 'Ljava/util/Locale;',
                slice_text(io, 315, 370))
# Objects (438-505)
emit_class_file(f'{ROOT}/java/util/objects.rs', 'java.util.Objects', 'Ljava/util/Objects;',
                slice_text(io, 438, 505))
# Charset (372-425) -> java/nio.rs
emit_class_file(f'{ROOT}/java/nio.rs', 'java.nio.charset.Charset', 'Ljava/nio/charset/Charset;',
                slice_text(io, 372, 425))
# lazy section (3-82): print stream -> io.rs, charset lazies -> nio.rs,
# prim class lazies -> java/lang/class.rs, bool lazies -> java/lang/boolean.rs
lazy_print = 'pub fn lazy_print_stream(vm: &mut Vm) -> JValue {\n    let class = vm\n        .ensure_class_by_desc("Ljava/io/PrintStream;")\n        .expect("PrintStream shim");\n    JValue::Obj(vm.arena.alloc(class, Vec::new(), Some(Native::PrintStream)))\n}\n\n'
with open(f'{ROOT}/java/io.rs') as f:
    io_body = f.read()
# insert ps_init + lazy_print_stream before the TABLE const
marker = '\n/// Native methods for Ljava/io/PrintStream;'
ps_init = slice_text(io, 427, 437)
io_body = io_body.replace(marker, lazy_print + ps_init + marker)
write(f'{ROOT}/java/io.rs', io_body)


def insert_after_header(body, extra):
    """Insert extra right after the 4-line header (use / blank / title / blank)."""
    lines = body.split('\n')
    return '\n'.join(lines[:4]) + '\n' + extra.rstrip('\n') + '\n' + '\n'.join(lines[4:])

charset_lazies = slice_text(io, 20, 35)
with open(f'{ROOT}/java/nio.rs') as f:
    nio_body = f.read()
write(f'{ROOT}/java/nio.rs', insert_after_header(nio_body, charset_lazies))

prim_lazies = slice_text(io, 37, 63) + slice_text(io, 76, 82)
with open(f'{ROOT}/java/lang/class.rs') as f:
    class_body = f.read()
write(f'{ROOT}/java/lang/class.rs', insert_after_header(class_body, prim_lazies))

bool_lazies = slice_text(io, 64, 75)
with open(f'{ROOT}/java/lang/boolean.rs') as f:
    bool_body = f.read()
write(f'{ROOT}/java/lang/boolean.rs', insert_after_header(bool_body, bool_lazies))

locale_lazy = 'pub fn lazy_opaque_locale(vm: &mut Vm) -> JValue {\n    let class = vm\n        .ensure_class_by_desc("Ljava/util/Locale;")\n        .expect("Locale shim");\n    JValue::Obj(vm.arena.alloc(class, Vec::new(), Some(Native::Opaque)))\n}\n\n'
with open(f'{ROOT}/java/util/locale.rs') as f:
    locale_body = f.read()
write(f'{ROOT}/java/util/locale.rs', insert_after_header(locale_body, locale_lazy))

# ---------------- text.rs -> java/text/* + java/util/timezone.rs ----------------
text = read(f'{ROOT}/text.rs')
# DateFormat/SimpleDateFormat impls + parse helpers (1-199)
emit_class_file(f'{ROOT}/java/text/simpledateformat.rs', 'java.text.SimpleDateFormat', 'Ljava/text/SimpleDateFormat;',
                slice_text(text, 1, 201))
# TimeZone (200-206)
emit_class_file(f'{ROOT}/java/util/timezone.rs', 'java.util.TimeZone', 'Ljava/util/TimeZone;',
                slice_text(text, 201, 206))
# ParsePosition (207-230)
emit_class_file(f'{ROOT}/java/text/parseposition.rs', 'java.text.ParsePosition', 'Ljava/text/ParsePosition;',
                slice_text(text, 207, 230))
# DateFormat (table only; impl shared with SimpleDateFormat)
emit_class_file(f'{ROOT}/java/text/dateformat.rs', 'java.text.DateFormat', 'Ljava/text/DateFormat;',
                '', extra_comment='// DateFormat shares the date_format_* impls with SimpleDateFormat (see simpledateformat.rs).\n')
write(f'{ROOT}/java/text/mod.rs',
      'mod dateformat;\nmod parseposition;\nmod simpledateformat;\n\npub(crate) use dateformat::*;\npub(crate) use parseposition::*;\npub(crate) use simpledateformat::*;\n')

print('done')
